# Generated by Django 3.2.11 on 2022-01-29 11:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechnicalSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('skill_name', models.CharField(max_length=25, verbose_name='Technical Skill Name')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Tech Skill Active')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'verbose_name': 'Technical skill',
                'verbose_name_plural': 'Technical skills',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('city_name', models.CharField(max_length=60, verbose_name='City Name')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is City Active?')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'verbose_name': 'City',
                'verbose_name_plural': 'Cities',
            },
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('name', models.CharField(max_length=60, verbose_name='Candidate Name')),
                ('email', models.EmailField(max_length=60, verbose_name='candidate Email')),
                ('phonenumber', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('address', models.CharField(max_length=255, verbose_name='Candidate Address')),
                ('city_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_city', to='users.city', verbose_name='City')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('tech_skills', models.ManyToManyField(related_name='candidate_skills', to='users.TechnicalSkill', verbose_name='TechnicalSkills')),
            ],
            options={
                'verbose_name': 'Candidate Details',
                'verbose_name_plural': 'Candidate Details',
            },
        ),
    ]
